from core.colors import *

BANNER = r"""
███████╗██╗     ███████╗██╗  ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗
██╔════╝██║     ██╔════╝╚██╗██╔╝╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝
█████╗  ██║     █████╗   ╚███╔╝    ██║   ██║   ██║██║   ██║██║     ███████╗
██╔══╝  ██║     ██╔══╝   ██╔██╗    ██║   ██║   ██║██║   ██║██║     ╚════██║
██║     ███████╗███████╗██╔╝ ██╗   ██║   ╚██████╔╝╚██████╔╝███████╗███████║
╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝
"""

def header():
    return cyan(BANNER) + "\n" + bold(magenta("                 FLEXTOOLS ")) + "\n" + dim("                 Defensive Web Security Testing Suite | Author: Mr.RezWithLove")

def line(title):
    return "\n"+bold(blue(title))+"\n"+dim("─"*70)

def root_help():
    print(header())
    print(line("USAGE"))
    print(f"  {paint_cmd('python main.py')} {paint_val('<command>')} {dim('[options]')}")
    print(line("COMMANDS"))
    rows=[
      ("detector","Deep multi-stage analysis for one target"),
      ("scan","Scan one URL or multiple URLs from a target file"),
      ("discover","Inspect URL, forms, and links for candidate parameters"),
      ("report","List generated JSON and TXT reports"),
    ]
    for a,b in rows: print(f"  {paint_cmd(a):<28} {b}")
    print(line("PROFILES"))
    print(f"  {green('soft'):<28} Conservative sampling, lower request volume")
    print(f"  {yellow('aggressive'):<28} More repeated validation and deeper sampling")
    print(line("ANALYSIS PIPELINE"))
    stages=[
      "Target validation","URL normalization","Query parameter mapping",
      "Baseline status sampling","Baseline response-length sampling",
      "Baseline timing sampling","SQL-related error signature checks",
      "Boolean differential comparison","Content similarity analysis",
      "Response-length anomaly analysis","HTTP status anomaly analysis",
      "Timing consistency analysis","DBMS-related fingerprinting",
      "Signal deduplication and aggregation","Confidence + severity scoring",
      "Terminal presentation","Automatic JSON/TXT reporting"
    ]
    for i,s in enumerate(stages,1): print(f"  {cyan(f'[{i:02d}]')} {s}")
    print(line("QUICK EXAMPLES"))
    examples=[
      ("Discover", "python main.py discover --url http://localhost:8080/index.php"),
      ("Detector", "python main.py detector --url http://localhost:8080/index.php?id=1"),
      ("Aggressive", "python main.py detector --url http://localhost:8080/index.php?id=1 --mode aggressive"),
      ("Multi-target", "python main.py scan --url-file targets.txt --mode aggressive --threads 5"),
      ("Reports", "python main.py report --list"),
    ]
    for label,cmd in examples:
        print(f"  {bold(label+':')}")
        print("    "+highlight(cmd))
    print(line("MORE HELP"))
    for cmd in ("detector","scan","discover","report"):
        print("  "+highlight(f"python main.py {cmd} --help"))

def highlight(s):
    parts=s.split()
    out=[]
    for x in parts:
        if x.startswith("--"): out.append(paint_opt(x))
        elif x in ("detector","scan","discover","report","python","main.py"): out.append(paint_cmd(x))
        elif x in ("soft","aggressive"): out.append(green(x) if x=="soft" else yellow(x))
        elif x.startswith("http"): out.append(paint_val(x))
        else: out.append(x)
    return " ".join(out)

def command_help(name):
    print(header())
    descriptions={
      "detector":"Run a structured multi-stage analysis against exactly one target.",
      "scan":"Run the detection pipeline against one target or a list of targets.",
      "discover":"Collect candidate parameter names from URL queries, forms, and links.",
      "report":"Inspect reports automatically generated by FlexTools.",
    }
    print(line(f"{name.upper()} COMMAND"))
    print(descriptions[name])
    print(line("USAGE"))
    usage={
      "detector":"python main.py detector --url URL [--mode soft|aggressive] [--timeout N] [--output DIR]",
      "scan":"python main.py scan (--url URL | --url-file FILE) [--mode soft|aggressive] [--threads N] [--timeout N] [--output DIR]",
      "discover":"python main.py discover --url URL [--timeout N]",
      "report":"python main.py report --list [--dir DIRECTORY]",
    }[name]
    print("  "+highlight(usage))
    print(line("OPTIONS"))
    opts={
      "detector":[("--url URL","Target URL containing existing query parameters"),("--mode PROFILE","soft or aggressive; default: soft"),("--timeout SECONDS","HTTP timeout; default: 10"),("--output DIRECTORY","Report directory; default: reports")],
      "scan":[("--url URL","One target URL"),("--url-file FILE","One URL per line"),("--mode PROFILE","soft or aggressive"),("--threads N","Parallel target workers"),("--timeout SECONDS","HTTP timeout"),("--output DIRECTORY","Report directory")],
      "discover":[("--url URL","Page to inspect"),("--timeout SECONDS","HTTP timeout; default: 10")],
      "report":[("--list","List report files"),("--dir DIRECTORY","Report directory; default: reports")],
    }[name]
    for a,b in opts: print(f"  {paint_opt(a):<34} {b}")
    print(line("EXAMPLES"))
    examples={
      "detector":[usage.replace("URL","http://localhost:8080/index.php?id=1").split(" [")[0],
                  "python main.py detector --url http://localhost:8080/index.php?id=1 --mode aggressive"],
      "scan":["python main.py scan --url-file targets.txt --mode soft",
              "python main.py scan --url-file targets.txt --mode aggressive --threads 5"],
      "discover":["python main.py discover --url http://localhost:8080/index.php"],
      "report":["python main.py report --list","python main.py report --list --dir results"],
    }[name]
    for e in examples: print("  "+highlight(e))
